CREATE TABLE IF NOT EXISTS sms_outbox (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  idempotency_key VARCHAR(191) NOT NULL,
  message_type VARCHAR(80) NOT NULL,
  receptor VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  payload_json JSON NULL,
  related_entity_type VARCHAR(80) NULL,
  related_entity_id BIGINT UNSIGNED NULL,
  status ENUM('pending','processing','retry','sent','dead') NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 6,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_at DATETIME NULL,
  locked_by VARCHAR(120) NULL,
  provider VARCHAR(80) NULL,
  provider_message_id VARCHAR(191) NULL,
  provider_response_json JSON NULL,
  sent_at DATETIME NULL,
  last_error VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sms_outbox_idempotency (idempotency_key),
  INDEX idx_sms_outbox_dequeue (status, available_at, id),
  INDEX idx_sms_outbox_entity (related_entity_type, related_entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_persian_ci;
