CREATE TABLE IF NOT EXISTS private_files (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category ENUM('consents','medical-records','patient-documents') NOT NULL,
  patient_id INT NOT NULL,
  medical_record_id INT NULL,
  appointment_id INT NULL,
  storage_name CHAR(42) NOT NULL UNIQUE,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  sha256 CHAR(64) NOT NULL,
  encryption_iv VARBINARY(12) NOT NULL,
  encryption_tag VARBINARY(16) NOT NULL,
  scan_status ENUM('clean','not_configured') NOT NULL,
  status ENUM('active','quarantined','archived','deleted') NOT NULL DEFAULT 'active',
  uploaded_by INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at DATETIME NULL,
  deleted_at DATETIME NULL,
  KEY idx_private_files_patient (patient_id, category, created_at),
  KEY idx_private_files_record (medical_record_id),
  KEY idx_private_files_appointment (appointment_id),
  CONSTRAINT fk_private_file_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,
  CONSTRAINT fk_private_file_record FOREIGN KEY (medical_record_id) REFERENCES medical_records(id) ON DELETE RESTRICT,
  CONSTRAINT fk_private_file_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_private_file_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
