CREATE TABLE IF NOT EXISTS clinical_break_glass_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  patient_id INT NOT NULL,
  doctor_id INT NOT NULL,
  requested_by INT NOT NULL,
  access_scope ENUM('read','write') NOT NULL DEFAULT 'read',
  reason VARCHAR(1000) NOT NULL,
  status ENUM('requested','approved','rejected','revoked','expired') NOT NULL DEFAULT 'requested',
  approved_by INT NULL,
  approval_reason VARCHAR(1000) NULL,
  approved_at DATETIME NULL,
  expires_at DATETIME NULL,
  rejected_by INT NULL,
  rejection_reason VARCHAR(1000) NULL,
  rejected_at DATETIME NULL,
  revoked_by INT NULL,
  revocation_reason VARCHAR(1000) NULL,
  revoked_at DATETIME NULL,
  last_used_at DATETIME NULL,
  use_count INT UNSIGNED NOT NULL DEFAULT 0,
  request_ip VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_break_glass_lookup (doctor_id, patient_id, status, expires_at),
  INDEX idx_break_glass_status (status, created_at),
  CONSTRAINT fk_break_glass_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,
  CONSTRAINT fk_break_glass_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE RESTRICT,
  CONSTRAINT fk_break_glass_requested FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_break_glass_approved FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_break_glass_rejected FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_break_glass_revoked FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_persian_ci;
